-- generated by: uv run python -m tests._schema --write
-- source-changelog-sha256: 1b5db4fabeecd4f0b3fbfe71c0beb64a8f5d4a9b85d4a1fd67d4bb267bf7f681
-- Regenerate after ANY change to db/changelog/db.changelog.xml.
CREATE TABLE expenses (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                amount TEXT NOT NULL,
                currency TEXT NOT NULL,
                merchant TEXT NOT NULL,
                date TEXT NOT NULL,
                category TEXT,
                user_id INTEGER NOT NULL,
                receipt_photo_id TEXT,
                created_at TEXT NOT NULL,
                deleted_at TEXT
            );
